-- Run once in Supabase: SQL Editor > New query > paste > Run

CREATE TABLE IF NOT EXISTS quizzes(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, slug TEXT UNIQUE NOT NULL, title TEXT NOT NULL,
  description TEXT DEFAULT '', active INTEGER DEFAULT 0, show_answers INTEGER DEFAULT 0,
  ask_name INTEGER DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS questions(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  position INTEGER NOT NULL, text TEXT NOT NULL, type TEXT NOT NULL CHECK(type IN ('mc','text')),
  options TEXT DEFAULT '[]', correct TEXT);
CREATE TABLE IF NOT EXISTS responses(
  id TEXT PRIMARY KEY, quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  name TEXT DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS answers(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, response_id TEXT NOT NULL REFERENCES responses(id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
  response_id TEXT REFERENCES responses(id) ON DELETE SET NULL, name TEXT DEFAULT '',
  body TEXT NOT NULL, is_read INTEGER DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS ix_q ON questions(quiz_id, position);
CREATE INDEX IF NOT EXISTS ix_r ON responses(quiz_id, created_at);
CREATE INDEX IF NOT EXISTS ix_a ON answers(response_id);
ALTER TABLE quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
